---
# 指定主机
- hosts: all
  # 指定在被管理的主机上执行任务的用户            
  remote_user: 'root'           
  tasks:
    # 任务列表                                         
    - name: hello world 
      # 调用command模块          
      shell: 'echo "hello world">/data/hello.txt'